let userAge = parseInt(prompt('Вкажіть ваш вік'))
if (userAge <= 6)
   document.write(`Ви відвідуєте садочок.`)
else if (userAge > 6 && userAge < 17)
   document.write(`Ви являєтесь школярем.`)
else if (userAge >= 17 && userAge < 23)
   document.write(`Ви являєтесь студентом.`)
else if (userAge >= 23 && userAge < 65)
   document.write(`Ви являєтесь працівником.`)
else if (userAge >= 65)
   document.write(`Ви на пенсії.`)